### ISSUE TITLE
Need setTimeout() to initiate jqPlot in afterTemplate()

### ISSUE THREAD

**Issue by sprijk** [esamattis/backbone.viewmaster#6]
I need to add setTimeout()

``` javascript
setTimeout(function() {
    $('selector').jqplot([series], options);
}, 0);
```

to initiate my plot in the afterTemplate() hook, because else jqPlot won't find the $('selector') element.

Way does it now work, and why doesn't afterTemplate() work out of the box? Is there a better way for this to work?

**Comment by esamattis** [comment]
I see two potential issues with your code.
1. The element is not in the dom tree yet. Use `this.$('selector')` rather than `$('selector')` to be able to reference elements before they are added to the dom.
2. The element you are selecting is not part of the template of the current view
   - You cannot access child view elements from parent for example. When manipulating child view elements do that in the child view.

**Comment by sprijk** [comment]
The jQuery plugin jqPlot initialises like this
- First add id '#jqplot_target_1' to the element -> This works
- Select the element by id, now using the $('#jqplot_target_1') selector -> No success!

(indeed Backbone selector this.$('#jqplot_target_1') is not used)

Is this where it goes wrong? How do I know when the DOM tree is ready?

**Comment by sprijk** [comment]
Maybe this is the error/resolution: http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful/779785#779785

**Comment by esamattis** [comment]
I just checked out the jqplot api and now I see the issue. It has an awful api. It requires that the container element has an id-attribute and that it is in the dom tree itself because it uses global full document selector to retrieve it. This is not very compatible with Backbone or ViewMaster. But you can workaround it if you really want to use it, but I'd recommend you find some other graphing lib.

To workaround it you just have to call the `$.jqplot` function when the view has been added to the dom. To do that simply add the `view.el` to dom for example like this `$("body").append(view.el)` before you calling `view.render()`.

**Comment by sprijk** [comment]
An awful API indeed :). Thanks for the hints and tips!
